server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_course?characterEncoding=utf-8
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath: cn/lqycloud/hrm/mapper/*Mapper.xml
  type-aliases-package: cn.lqycloud.hrm.domain,cn.lqycloud.hrm.query